--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2026. 04. 13. 13:03:13
-- Server version: 5.7.44
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS mealrecipes;

CREATE DATABASE IF NOT EXISTS mealrecipes
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE mealrecipes;

--
-- Create table `meal_of_days`
--
CREATE TABLE IF NOT EXISTS meal_of_days (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  meal_of_day VARCHAR(25) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `meal_of_days_meal_of_day_unique` on table `meal_of_days`
--
ALTER TABLE meal_of_days 
  ADD UNIQUE INDEX meal_of_days_meal_of_day_unique(meal_of_day);

--
-- Create table `meals`
--
CREATE TABLE IF NOT EXISTS meals (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  meal VARCHAR(25) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `meals_meal_unique` on table `meals`
--
ALTER TABLE meals 
  ADD UNIQUE INDEX meals_meal_unique(meal);

--
-- Create table `recipes`
--
CREATE TABLE IF NOT EXISTS recipes (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(125) NOT NULL,
  description TEXT NOT NULL,
  picture VARCHAR(125) NOT NULL,
  person INT(11) NOT NULL,
  meal_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `recipes_name_unique` on table `recipes`
--
ALTER TABLE recipes 
  ADD UNIQUE INDEX recipes_name_unique(name);

--
-- Create index `recipes_picture_unique` on table `recipes`
--
ALTER TABLE recipes 
  ADD UNIQUE INDEX recipes_picture_unique(picture);

--
-- Create foreign key
--
ALTER TABLE recipes 
  ADD CONSTRAINT recipes_meal_id_foreign FOREIGN KEY (meal_id)
    REFERENCES meals(id);

--
-- Create table `meal_requirements`
--
CREATE TABLE IF NOT EXISTS meal_requirements (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  meal_of_day_id BIGINT(20) UNSIGNED NOT NULL,
  meal_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `meal_requirements_meal_of_day_id_meal_id_unique` on table `meal_requirements`
--
ALTER TABLE meal_requirements 
  ADD UNIQUE INDEX meal_requirements_meal_of_day_id_meal_id_unique(meal_of_day_id, meal_id);

--
-- Create foreign key
--
ALTER TABLE meal_requirements 
  ADD CONSTRAINT meal_requirements_meal_id_foreign FOREIGN KEY (meal_id)
    REFERENCES meals(id);

--
-- Create foreign key
--
ALTER TABLE meal_requirements 
  ADD CONSTRAINT meal_requirements_meal_of_day_id_foreign FOREIGN KEY (meal_of_day_id)
    REFERENCES meal_of_days(id);

--
-- Create table `units`
--
CREATE TABLE IF NOT EXISTS units (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  unit VARCHAR(25) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 16,
AVG_ROW_LENGTH = 1092,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `units_unit_unique` on table `units`
--
ALTER TABLE units 
  ADD UNIQUE INDEX units_unit_unique(unit);

--
-- Create table `raw_ingredients`
--
CREATE TABLE IF NOT EXISTS raw_ingredients (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  raw_ingredient VARCHAR(125) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 324,
AVG_ROW_LENGTH = 50,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `raw_ingredients_raw_ingredient_unique` on table `raw_ingredients`
--
ALTER TABLE raw_ingredients 
  ADD UNIQUE INDEX raw_ingredients_raw_ingredient_unique(raw_ingredient);

--
-- Create table `ingredients`
--
CREATE TABLE IF NOT EXISTS ingredients (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  recipe_id BIGINT(20) UNSIGNED NOT NULL,
  raw_ingredient_id BIGINT(20) UNSIGNED NOT NULL,
  amount INT(11) NOT NULL,
  unit_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 311,
AVG_ROW_LENGTH = 158,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `ingredients_recipe_id_raw_ingredient_id_unique` on table `ingredients`
--
ALTER TABLE ingredients 
  ADD UNIQUE INDEX ingredients_recipe_id_raw_ingredient_id_unique(recipe_id, raw_ingredient_id);

--
-- Create foreign key
--
ALTER TABLE ingredients 
  ADD CONSTRAINT ingredients_raw_ingredient_id_foreign FOREIGN KEY (raw_ingredient_id)
    REFERENCES raw_ingredients(id);

--
-- Create foreign key
--
ALTER TABLE ingredients 
  ADD CONSTRAINT ingredients_recipe_id_foreign FOREIGN KEY (recipe_id)
    REFERENCES recipes(id);

--
-- Create foreign key
--
ALTER TABLE ingredients 
  ADD CONSTRAINT ingredients_unit_id_foreign FOREIGN KEY (unit_id)
    REFERENCES units(id);

--
-- Create table `weekdays`
--
CREATE TABLE IF NOT EXISTS weekdays (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  day VARCHAR(25) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `weekdays_day_unique` on table `weekdays`
--
ALTER TABLE weekdays 
  ADD UNIQUE INDEX weekdays_day_unique(day);

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL,
  role INT(11) NOT NULL DEFAULT 3,
  email_verified_at TIMESTAMP NULL DEFAULT NULL,
  password VARCHAR(191) NOT NULL,
  remember_token VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `users_email_unique` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX users_email_unique(email);

--
-- Create table `favorite_recipes`
--
CREATE TABLE IF NOT EXISTS favorite_recipes (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT(20) UNSIGNED NOT NULL,
  recipe_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `favorite_recipes_user_id_recipe_id_unique` on table `favorite_recipes`
--
ALTER TABLE favorite_recipes 
  ADD UNIQUE INDEX favorite_recipes_user_id_recipe_id_unique(user_id, recipe_id);

--
-- Create foreign key
--
ALTER TABLE favorite_recipes 
  ADD CONSTRAINT favorite_recipes_recipe_id_foreign FOREIGN KEY (recipe_id)
    REFERENCES recipes(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE favorite_recipes 
  ADD CONSTRAINT favorite_recipes_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE;

--
-- Create table `days`
--
CREATE TABLE IF NOT EXISTS days (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  weekday_id BIGINT(20) UNSIGNED NOT NULL,
  user_id BIGINT(20) UNSIGNED NOT NULL,
  recipe_id BIGINT(20) UNSIGNED NOT NULL,
  meal_requirement_id BIGINT(20) UNSIGNED NOT NULL,
  plan_week INT(10) UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 50,
AVG_ROW_LENGTH = 334,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `days_user_planweek_weekday_mealreq_unique` on table `days`
--
ALTER TABLE days 
  ADD UNIQUE INDEX days_user_planweek_weekday_mealreq_unique(user_id, plan_week, weekday_id, meal_requirement_id);

--
-- Create foreign key
--
ALTER TABLE days 
  ADD CONSTRAINT days_meal_requirement_id_foreign FOREIGN KEY (meal_requirement_id)
    REFERENCES meal_requirements(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE days 
  ADD CONSTRAINT days_recipe_id_foreign FOREIGN KEY (recipe_id)
    REFERENCES recipes(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE days 
  ADD CONSTRAINT days_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE days 
  ADD CONSTRAINT days_weekday_id_foreign FOREIGN KEY (weekday_id)
    REFERENCES weekdays(id);

--
-- Create table `sessions`
--
CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(191) NOT NULL,
  user_id BIGINT(20) UNSIGNED DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  payload LONGTEXT NOT NULL,
  last_activity INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `sessions_last_activity_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_last_activity_index(last_activity);

--
-- Create index `sessions_user_id_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_user_id_index(user_id);

--
-- Create table `personal_access_tokens`
--
CREATE TABLE IF NOT EXISTS personal_access_tokens (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  tokenable_type VARCHAR(191) NOT NULL,
  tokenable_id BIGINT(20) UNSIGNED NOT NULL,
  name TEXT NOT NULL,
  token VARCHAR(64) NOT NULL,
  abilities TEXT DEFAULT NULL,
  last_used_at TIMESTAMP NULL DEFAULT NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `personal_access_tokens_expires_at_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_expires_at_index(expires_at);

--
-- Create index `personal_access_tokens_token_unique` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD UNIQUE INDEX personal_access_tokens_token_unique(token);

--
-- Create index `personal_access_tokens_tokenable_type_tokenable_id_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_tokenable_type_tokenable_id_index(tokenable_type, tokenable_id);

--
-- Create table `password_reset_tokens`
--
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  email VARCHAR(191) NOT NULL,
  token VARCHAR(191) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (email)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `migrations`
--
CREATE TABLE IF NOT EXISTS migrations (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  migration VARCHAR(191) NOT NULL,
  batch INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 18,
AVG_ROW_LENGTH = 963,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `job_batches`
--
CREATE TABLE IF NOT EXISTS job_batches (
  id VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  total_jobs INT(11) NOT NULL,
  pending_jobs INT(11) NOT NULL,
  failed_jobs INT(11) NOT NULL,
  failed_job_ids LONGTEXT NOT NULL,
  options MEDIUMTEXT DEFAULT NULL,
  cancelled_at INT(11) DEFAULT NULL,
  created_at INT(11) NOT NULL,
  finished_at INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `jobs`
--
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  queue VARCHAR(191) NOT NULL,
  payload LONGTEXT NOT NULL,
  attempts TINYINT(3) UNSIGNED NOT NULL,
  reserved_at INT(10) UNSIGNED DEFAULT NULL,
  available_at INT(10) UNSIGNED NOT NULL,
  created_at INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `jobs_queue_index` on table `jobs`
--
ALTER TABLE jobs 
  ADD INDEX jobs_queue_index(queue);

--
-- Create table `failed_jobs`
--
CREATE TABLE IF NOT EXISTS failed_jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(191) NOT NULL,
  `connection` TEXT NOT NULL,
  queue TEXT NOT NULL,
  payload LONGTEXT NOT NULL,
  exception LONGTEXT NOT NULL,
  failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `failed_jobs_uuid_unique` on table `failed_jobs`
--
ALTER TABLE failed_jobs 
  ADD UNIQUE INDEX failed_jobs_uuid_unique(uuid);

--
-- Create table `cache_locks`
--
CREATE TABLE IF NOT EXISTS cache_locks (
  `key` VARCHAR(191) NOT NULL,
  owner VARCHAR(191) NOT NULL,
  expiration INT(11) NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `cache`
--
CREATE TABLE IF NOT EXISTS cache (
  `key` VARCHAR(191) NOT NULL,
  value MEDIUMTEXT NOT NULL,
  expiration INT(11) NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

-- 
-- Dumping data for table meal_of_days
--
INSERT INTO meal_of_days VALUES
(1, 'Reggeli', NULL, NULL),
(2, 'Ebéd', NULL, NULL),
(3, 'Vacsora', NULL, NULL);

-- 
-- Dumping data for table meals
--
INSERT INTO meals VALUES
(1, 'Reggeli', NULL, NULL),
(2, 'Előétel', NULL, NULL),
(3, 'Leves', NULL, NULL),
(4, 'Főétel', NULL, NULL),
(5, 'Desszert', NULL, NULL);

-- 
-- Dumping data for table units
--
INSERT INTO units VALUES
(1, 'g', NULL, NULL),
(2, 'dkg', NULL, NULL),
(3, 'kg', NULL, NULL),
(4, 'ml', NULL, NULL),
(5, 'dl', NULL, NULL),
(6, 'l', NULL, NULL),
(7, 'tk', NULL, NULL),
(8, 'ek', NULL, NULL),
(9, 'csipet', NULL, NULL),
(10, 'db', NULL, NULL),
(11, 'csésze', NULL, NULL),
(12, 'bögre', NULL, NULL),
(13, 'szelet', NULL, NULL),
(14, 'fej', NULL, NULL),
(15, 'gerezd', NULL, NULL);

-- 
-- Dumping data for table raw_ingredients
--
INSERT INTO raw_ingredients VALUES
(1, 'tojás', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(2, 'só', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(3, 'fekete bors', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(4, 'bors', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(5, 'vaj', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(6, 'olaj', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(7, 'napraforgóolaj', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(8, 'olívaolaj', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(9, 'extra szűz olívaolaj', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(10, 'zabpehely', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(11, 'apró zabpehely', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(12, 'nagy szemű zabpehely', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(13, 'tej', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(14, 'teljes tej', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(15, 'félzsíros tej', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(16, 'laktózmentes tej', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(17, 'kecsketej', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(18, 'mandulatej', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(19, 'rizstej', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(20, 'szójatej', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(21, 'kókusztej', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(22, 'méz', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(23, 'akácméz', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(24, 'hársméz', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(25, 'repce méz', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(26, 'agávé szirup', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(27, 'juharszirup', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(28, 'datolya szirup', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(29, 'stevia', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(30, 'eritrit', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(31, 'xilit', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(32, 'liszt', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(33, 'finomliszt', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(34, 'rétesliszt', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(35, 'kenyérliszt', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(36, 'pizza liszt', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(37, 'teljes kiőrlésű liszt', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(38, 'tönkölyliszt', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(39, 'rozsliszt', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(40, 'kukoricaliszt', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(41, 'rizsliszt', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(42, 'cukor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(43, 'kristálycukor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(44, 'porcukor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(45, 'barnacukor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(46, 'nád­cukor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(47, 'kókuszcukor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(48, 'vaníliás cukor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(49, 'fahéjas cukor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(50, 'kakaópor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(51, 'holland kakaópor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(52, 'csokoládé', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(53, 'étcsokoládé', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(54, '70%-os csokoládé', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(55, '85%-os csokoládé', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(56, 'tejcsokoládé', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(57, 'fehér csokoládé', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(58, 'csokicsepp', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(59, 'fokhagyma', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(60, 'vöröshagyma', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(61, 'lilahagyma', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(62, 'póréhagyma', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(63, 'újhagyma', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(64, 'snidling', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(65, 'burgonya', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(66, 'újburgonya', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(67, 'édesburgonya', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(68, 'lila burgonya', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(69, 'sárgarépa', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(70, 'petrezselyemgyökér', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(71, 'zeller', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(72, 'zellergumó', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(73, 'zellerszár', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(74, 'cékla', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(75, 'fehérrépa', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(76, 'retek', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(77, 'jégcsapretek', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(78, 'paradicsom', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(79, 'koktélparadicsom', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(80, 'san marzano paradicsom', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(81, 'paradicsompüré', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(82, 'paradicsomszósz', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(83, 'passata', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(84, 'paprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(85, 'zöldpaprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(86, 'kaliforniai paprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(87, 'piros paprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(88, 'sárga paprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(89, 'hegyes erős paprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(90, 'csilipaprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(91, 'jalapeno paprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(92, 'habanero paprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(93, 'pirospaprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(94, 'füstölt paprika', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(95, 'kömény', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(96, 'egész kömény', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(97, 'őrölt kömény', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(98, 'fahéj', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(99, 'ceyloni fahéj', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(100, 'szegfűszeg', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(101, 'szerecsendió', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(102, 'szerecsendió virág', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(103, 'gyömbér', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(104, 'friss gyömbér', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(105, 'őrölt gyömbér', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(106, 'kurkuma', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(107, 'koriander', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(108, 'egész koriander', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(109, 'őrölt koriander', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(110, 'római kömény', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(111, 'mustármag', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(112, 'majoranna', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(113, 'oregánó', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(114, 'bazsalikom', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(115, 'thai bazsalikom', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(116, 'kakukkfű', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(117, 'rozmaring', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(118, 'babérlevél', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(119, 'kapor', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(120, 'petrezselyem', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(121, 'menta', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(122, 'citromfű', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(123, 'citromlé', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(124, 'lime', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(125, 'lime lé', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(126, 'narancs', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(127, 'mandarin', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(128, 'grapefruit', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(129, 'alma', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(130, 'zöld alma', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(131, 'körte', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(132, 'banán', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(133, 'eper', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(134, 'málna', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(135, 'áfonya', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(136, 'ribizli', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(137, 'szeder', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(138, 'barack', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(139, 'őszibarack', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(140, 'sárgabarack', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(141, 'szilva', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(142, 'cseresznye', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(143, 'meggy', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(144, 'ananász', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(145, 'mangó', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(146, 'papaya', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(147, 'kivi', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(148, 'gránátalma', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(149, 'szőlő', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(150, 'mazsola', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(151, 'datolya', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(152, 'füge', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(153, 'dió', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(154, 'darált dió', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(155, 'pekándió', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(156, 'mogyoró', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(157, 'földimogyoró', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(158, 'mandula', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(159, 'kesudió', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(160, 'pisztácia', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(161, 'makadámdió', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(162, 'kókuszreszelék', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(163, 'kókusztejpor', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(164, 'chia mag', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(165, 'lenmag', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(166, 'napraforgómag', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(167, 'tökmag', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(168, 'szezámmag', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(169, 'mák', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(170, 'lekvár', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(171, 'baracklekvár', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(172, 'eperlekvár', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(173, 'szilvalekvár', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(174, 'dzsem', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(175, 'narancslekvár', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(176, 'nutella', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(177, 'mogyorókrém', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(178, 'tojásfehérje', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(179, 'tojássárgája', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(180, 'főzőtejszín', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(181, 'habtejszín', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(182, 'tejföl', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(183, 'joghurt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(184, 'natúr joghurt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(185, 'görög joghurt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(186, 'kefir', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(187, 'író', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(188, 'skyr', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(189, 'sózott vaj', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(190, 'tisztított vaj', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(191, 'margarin', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(192, 'sertészsír', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(193, 'libazsír', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(194, 'kacsazsír', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(195, 'fokhagymaolaj', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(196, 'chiliolaj', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(197, 'szezámolaj', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(198, 'kókuszolaj', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(199, 'csirkehús', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(200, 'csirkecomb', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(201, 'csirkemell', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(202, 'pulykamell', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(203, 'pulykahús', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(204, 'kacsamell', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(205, 'libamell', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(206, 'sertéshús', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(207, 'sertéscomb', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(208, 'sertéstarja', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(209, 'sertésszűz', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(210, 'malachús', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(211, 'marhahús', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(212, 'marhalábszár', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(213, 'marhacomb', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(214, 'bélszín', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(215, 'rostélyos', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(216, 'darált sertéshús', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(217, 'darált marhahús', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(218, 'darált pulykahús', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(219, 'kolbász', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(220, 'csabai kolbász', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(221, 'gyulai kolbász', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(222, 'füstölt kolbász', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(223, 'virsli', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(224, 'sonka', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(225, 'füstölt sonka', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(226, 'prosciutto', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(227, 'bacon', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(228, 'pancetta', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(229, 'szalonna', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(230, 'abált szalonna', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(231, 'libamáj', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(232, 'kacsamáj', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(233, 'hal', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(234, 'halfélék', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(235, 'halfilé', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(236, 'harcsa filé', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(237, 'ponty', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(238, 'hekk', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(239, 'tőkehal', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(240, 'lazac', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(241, 'lazacfilé', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(242, 'pisztráng', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(243, 'tonhal', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(244, 'tonhalkonzerv', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(245, 'makréla', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(246, 'szardínia', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(247, 'rák', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(248, 'garnéla', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(249, 'tintahal', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(250, 'polip', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(251, 'rizs', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(252, 'fehér rizs', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(253, 'jázmin rizs', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(254, 'basmati rizs', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(255, 'barna rizs', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(256, 'vad rizs', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(257, 'arborio rizs', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(258, 'sushi rizs', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(259, 'tészta', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(260, 'száraztészta', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(261, 'friss tészta', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(262, 'spagetti', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(263, 'penne', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(264, 'fusilli', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(265, 'farfalle', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(266, 'tagliatelle', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(267, 'linguine', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(268, 'lasagne lap', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(269, 'gnocchi', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(270, 'tarhonya', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(271, 'bulgur', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(272, 'kuszkusz', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(273, 'quinoa', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(274, 'köles', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(275, 'hajdina', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(276, 'árpagyöngy', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(277, 'lencse', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(278, 'vöröslencse', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(279, 'zöld lencse', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(280, 'fekete lencse', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(281, 'csicseriborsó', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(282, 'fehér bab', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(283, 'vörös bab', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(284, 'fekete bab', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(285, 'szójabab', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(286, 'zöldborsó', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(287, 'cukorborsó', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(288, 'sárgaborsó', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(289, 'kukorica', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(290, 'csemegekukorica', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(291, 'sajt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(292, 'trappista sajt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(293, 'edami sajt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(294, 'emmentáli sajt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(295, 'gouda sajt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(296, 'cheddar sajt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(297, 'parmezán', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(298, 'grana padano', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(299, 'pecorino', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(300, 'mozzarella', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(301, 'buffalo mozzarella', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(302, 'burrata', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(303, 'ricotta', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(304, 'mascarpone', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(305, 'feta sajt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(306, 'kecskesajt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(307, 'camembert', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(308, 'brie', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(309, 'túró', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(310, 'krémsajt', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(311, 'savanyú káposzta', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(312, 'zöldség', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(313, 'kenyér', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(314, 'uborka', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(315, 'avokádó', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(316, 'élesztő', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(317, 'víz', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(318, 'saláta', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(319, 'zsemlemorzsa', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(320, 'sütőpor', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(321, 'kávé', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(322, 'szalámi', '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(323, 'citrom', '2026-03-31 10:51:54', '2026-03-31 10:51:54');

-- 
-- Dumping data for table weekdays
--
INSERT INTO weekdays VALUES
(1, 'Hétfő', NULL, NULL),
(2, 'Kedd', NULL, NULL),
(3, 'Szerda', NULL, NULL),
(4, 'Csütörtök', NULL, NULL),
(5, 'Péntek', NULL, NULL),
(6, 'Szombat', NULL, NULL),
(7, 'Vasárnap', NULL, NULL);

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'Admin', 'admin@example.com', 1, '2026-03-31 10:51:52', '$2y$12$A8F3p/gbihCgApJ0qARo9.1HDYaqR5PgY3T0KKEAmXhaADRtXdKey', 'cgUOL6BzsG', '2026-03-31 10:51:53', '2026-03-31 10:51:53'),
(2, 'Felhasználó', 'felhasznalo@example.com', 2, '2026-03-31 10:51:53', '$2y$12$bDHKmiOmb4X0BJ1Sj1KIMe8ISZQf.c8C61oFKXGCQr.o7/fmXNI8K', 'wvDd2NUB0y', '2026-03-31 10:51:53', '2026-03-31 10:51:53');

-- 
-- Dumping data for table recipes
--
INSERT INTO recipes VALUES
(1, 'Rántotta', 'Egyszerű tojásos reggeli', 'Pictures/Rántotta.jpg', 4, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(2, 'Tükörtojás', 'Serpenyőben sült tojás', 'Pictures/Tükörtojás.jpg', 4, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(3, 'Zabkása', 'Egészséges reggeli étel', 'Pictures/Zabkása.jpg', 4, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(4, 'Palacsinta reggelire', 'Édes reggeli palacsinta', 'Pictures/Palacsinta reggelire.jpg', 4, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(5, 'Melegszendvics', 'Sütőben sült szendvics', 'Pictures/Melegszendvics.jpg', 4, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(6, 'Tojásrántotta zöldségekkel', 'Egészséges tojásos reggeli', 'Pictures/Tojásrántotta zöldségekkel.jpg', 4, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(7, 'Avokádós pirítós', 'Modern reggeli fogás', 'Pictures/Avokádós pirítós.jpg', 4, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(8, 'Joghurt müzlivel', 'Könnyű reggeli étel', 'Pictures/Joghurt müzlivel.jpg', 4, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(9, 'Kakaós csiga', 'Édes péksütemény', 'Pictures/Kakaós csiga.jpg', 4, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(10, 'Croissant', 'Francia vajas péksütemény', 'Pictures/Croissant.jpg', 4, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(11, 'Cézár saláta', 'Klasszikus csirkés saláta', 'Pictures/Cézár saláta.jpg', 4, 2, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(12, 'Görög saláta', 'Friss zöldséges előétel', 'Pictures/Görög saláta.jpg', 4, 2, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(13, 'Bruschetta', 'Pirított kenyér paradicsommal', 'Pictures/Bruschetta.jpg', 4, 2, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(14, 'Hidegtál', 'Vegetáriánus falatkák', 'Pictures/Hidegtál.jpg', 4, 2, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(15, 'Tojáskrémes kenyér', 'Egyszerű hideg előétel', 'Pictures/Tojáskrémes kenyér.jpg', 4, 2, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(16, 'Sajttál', 'Válogatott sajtok', 'Pictures/Sajttál.jpg', 4, 2, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(17, 'Szalámis falatok', 'Hideg húsos előétel', 'Pictures/Szalámis falatok.jpg', 4, 2, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(18, 'Caprese saláta', 'Mozzarella paradicsommal', 'Pictures/Caprese saláta.jpg', 4, 2, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(19, 'Töltött tojás', 'Majonézes tojásétel', 'Pictures/Töltött tojás.jpg', 4, 2, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(20, 'Sonkatekercs', 'Sonkába tekert krémes töltelék', 'Pictures/Sonkatekercs.jpg', 4, 2, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(21, 'Gulyásleves', 'Hagyományos magyar leves', 'Pictures/Gulyásleves.jpg', 4, 3, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(22, 'Húsleves gazdagon', 'Lassan főzött klasszikus leves', 'Pictures/Húsleves gazdagon.jpg', 4, 3, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(23, 'Paradicsomleves', 'Édeskés paradicsomos leves', 'Pictures/Paradicsomleves.jpg', 4, 3, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(24, 'Zöldségleves', 'Friss zöldségekből készült leves', 'Pictures/Zöldségleves.jpg', 4, 3, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(25, 'Krémleves', 'Gazdag állagú krémes leves', 'Pictures/Krémleves.jpg', 4, 3, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(26, 'Bableves', 'Tartalmas babos leves', 'Pictures/Bableves.jpg', 4, 3, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(27, 'Lencseleves', 'Hagyományos lencsés leves', 'Pictures/Lencseleves.jpg', 4, 3, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(28, 'Halászlé', 'Fűszeres magyar halleves', 'Pictures/Halászlé.jpg', 4, 3, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(29, 'Karfiolleves', 'Könnyű zöldségleves', 'Pictures/Karfiolleves.jpg', 4, 3, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(30, 'Almaleves', 'Hidegen is fogyasztható gyümölcsleves', 'Pictures/Almaleves.jpg', 4, 3, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(31, 'Paprikás krumpli', 'Hagyományos magyar egytálétel kolbásszal', 'Pictures/Paprikás Krumpli.jpg', 4, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(32, 'Rántott hús burgonyával', 'Ropogós panírozott sertéshús körettel', 'Pictures/Rántott hús burgonyával.jpg', 4, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(33, 'Marhapörkölt', 'Szaftos marhapörkölt magyarosan', 'Pictures/Marhapörkölt.jpg', 4, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(34, 'Spagetti bolognai', 'Paradicsomos húsos tésztaétel', 'Pictures/Spagetti bolognai.jpg', 4, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(35, 'Csirkepaprikás', 'Tejfölös-paprikás csirkés főétel', 'Pictures/Csirkepaprikás.jpg', 4, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(36, 'Lasagne', 'Olasz réteges tésztaétel', 'Pictures/Lasagne.jpg', 4, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(37, 'Töltött káposzta', 'Káposztalevélbe töltött húsos étel', 'Pictures/Töltött káposzta.jpg', 4, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(38, 'Rakott krumpli', 'Burgonyás-tejfölös sütött étel', 'Pictures/Rakott krumpli.jpg', 4, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(39, 'Grillezett csirkemell', 'Egészséges sült csirkehús', 'Pictures/Grillezett csirkemell.jpg', 4, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(40, 'Rántott sajt', 'Bundázott sült sajt', 'Pictures/Rántott sajt.jpg', 4, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(41, 'Palacsinta', 'Édes töltött desszert', 'Pictures/Palacsinta.jpg', 4, 5, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(42, 'Somlói galuska', 'Magyar klasszikus desszert', 'Pictures/Somlói galuska.jpg', 4, 5, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(43, 'Tiramisu', 'Olasz krémes desszert', 'Pictures/Tiramisu.jpg', 4, 5, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(44, 'Almás pite', 'Fahéjas almás sütemény', 'Pictures/Almás pite.jpg', 4, 5, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(45, 'Chocolate brownie', 'Puha csokoládés sütemény', 'Pictures/Chocolate brownie.jpg', 4, 5, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(46, 'Sajttorta', 'Krémes sült desszert', 'Pictures/Sajttorta.jpg', 4, 5, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(47, 'Piskótatekercs', 'Krémmel töltött sütemény', 'Pictures/Piskótatekercs.jpg', 4, 5, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(48, 'Muffin', 'Könnyű egyadagos sütemény', 'Pictures/Muffin.jpg', 4, 5, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(49, 'Rizskoch', 'Sült rizses desszert', 'Pictures/Rizskoch.jpg', 4, 5, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(50, 'Aranygaluska', 'Diós kelt tészta desszert', 'Pictures/Aranygaluska.jpg', 4, 5, '2026-03-31 10:51:54', '2026-03-31 10:51:54');

-- 
-- Dumping data for table meal_requirements
--
INSERT INTO meal_requirements VALUES
(1, 1, 1, NULL, '2026-03-31 10:52:16'),
(2, 2, 2, NULL, NULL),
(3, 2, 3, NULL, NULL),
(4, 2, 4, NULL, NULL),
(5, 2, 5, NULL, NULL),
(6, 3, 4, NULL, NULL),
(7, 3, 5, NULL, NULL);

-- 
-- Dumping data for table sessions
--
-- Table mealrecipes.sessions does not contain any data (it is empty)

-- 
-- Dumping data for table personal_access_tokens
--
INSERT INTO personal_access_tokens VALUES
(1, 'App\\Models\\User', 1, '1day-role:1', '39d5436758132675991b7158798a4e9c5e4711685a6098ac8b8227758a74957e', '["*"]', '2026-03-31 10:52:16', '2026-04-01 09:47:15', '2026-03-31 09:47:15', '2026-03-31 10:52:16');

-- 
-- Dumping data for table password_reset_tokens
--
-- Table mealrecipes.password_reset_tokens does not contain any data (it is empty)

-- 
-- Dumping data for table migrations
--
INSERT INTO migrations VALUES
(1, '0001_01_01_000000_create_users_table', 1),
(2, '0001_01_01_000001_create_cache_table', 1),
(3, '0001_01_01_000002_create_jobs_table', 1),
(4, '2025_11_04_102115_create_personal_access_tokens_table', 1),
(5, '2025_11_18_081107_add_role_to_users_table', 1),
(6, '2026_01_15_121114_create_weekdays_table', 1),
(7, '2026_01_16_081426_create_meals_table', 1),
(8, '2026_01_16_081525_create_meal_of_days_table', 1),
(9, '2026_01_16_081603_create_units_table', 1),
(10, '2026_01_16_081658_create_raw_ingredients_table', 1),
(11, '2026_01_16_081739_create_recipes_table', 1),
(12, '2026_01_16_081900_create_meal_requirements_table', 1),
(13, '2026_01_16_082253_create_days_table', 1),
(14, '2026_01_16_082310_create_ingredients_table', 1),
(15, '2026_03_04_120000_add_plan_week_to_days_table', 1),
(16, '2026_03_23_090000_create_favorite_recipes_table', 1),
(17, '2026_03_31_090000_restrict_delete_on_weekdays', 1);

-- 
-- Dumping data for table job_batches
--
-- Table mealrecipes.job_batches does not contain any data (it is empty)

-- 
-- Dumping data for table jobs
--
-- Table mealrecipes.jobs does not contain any data (it is empty)

-- 
-- Dumping data for table ingredients
--
INSERT INTO ingredients VALUES
(1, 1, 1, 4, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(2, 1, 2, 1, 9, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(3, 1, 3, 1, 9, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(4, 1, 5, 10, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(5, 2, 1, 2, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(6, 2, 2, 1, 9, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(7, 2, 3, 1, 9, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(8, 2, 5, 10, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(9, 3, 10, 80, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(10, 3, 13, 250, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(11, 3, 22, 1, 8, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(12, 3, 98, 1, 7, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(13, 3, 132, 1, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(14, 4, 1, 2, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(15, 4, 2, 1, 9, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(16, 4, 5, 30, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(17, 4, 13, 300, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(18, 4, 32, 250, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(19, 4, 42, 20, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(20, 5, 5, 20, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(21, 5, 78, 1, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(22, 5, 113, 1, 7, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(23, 5, 224, 4, 13, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(24, 5, 291, 100, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(25, 5, 313, 4, 13, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(26, 6, 1, 4, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(27, 6, 2, 1, 9, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(28, 6, 3, 1, 9, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(29, 6, 6, 1, 8, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(30, 6, 60, 1, 14, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(31, 6, 78, 1, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(32, 6, 84, 1, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(33, 7, 1, 1, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(34, 7, 2, 1, 9, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(35, 7, 3, 1, 9, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(36, 7, 123, 1, 8, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(37, 7, 313, 2, 13, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(38, 7, 315, 1, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(39, 8, 10, 40, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(40, 8, 22, 1, 8, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(41, 8, 132, 1, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(42, 8, 153, 20, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(43, 8, 183, 200, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(44, 9, 1, 1, 10, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(45, 9, 2, 1, 9, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(46, 9, 5, 50, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(47, 9, 13, 200, 4, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(48, 9, 32, 300, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(49, 9, 42, 50, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(50, 9, 50, 20, 1, '2026-03-31 10:51:54', '2026-03-31 10:51:54'),
(51, 9, 316, 5, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(52, 10, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(53, 10, 5, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(54, 10, 13, 150, 4, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(55, 10, 32, 300, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(56, 10, 42, 30, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(57, 10, 316, 7, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(58, 11, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(59, 11, 3, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(60, 11, 8, 2, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(61, 11, 59, 1, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(62, 11, 123, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(63, 11, 201, 300, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(64, 11, 297, 40, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(65, 11, 313, 2, 13, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(66, 11, 318, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(67, 12, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(68, 12, 8, 2, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(69, 12, 78, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(70, 12, 113, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(71, 12, 305, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(72, 12, 314, 1, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(73, 13, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(74, 13, 8, 2, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(75, 13, 59, 2, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(76, 13, 78, 3, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(77, 13, 114, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(78, 13, 313, 4, 13, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(79, 14, 78, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(80, 14, 224, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(81, 14, 291, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(82, 14, 313, 4, 13, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(83, 14, 314, 1, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(84, 15, 1, 4, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(85, 15, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(86, 15, 3, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(87, 15, 5, 20, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(88, 15, 64, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(89, 15, 313, 4, 13, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(90, 16, 292, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(91, 16, 293, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(92, 16, 295, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(93, 16, 296, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(94, 16, 297, 50, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(95, 17, 5, 20, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(96, 17, 313, 4, 13, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(97, 17, 314, 1, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(98, 17, 322, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(99, 18, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(100, 18, 8, 2, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(101, 18, 78, 3, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(102, 18, 114, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(103, 18, 300, 250, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(104, 19, 1, 6, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(105, 19, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(106, 19, 3, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(107, 19, 5, 20, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(108, 19, 111, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(109, 20, 3, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(110, 20, 64, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(111, 20, 224, 8, 13, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(112, 20, 310, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(113, 21, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(114, 21, 60, 2, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(115, 21, 65, 400, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(116, 21, 81, 2, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(117, 21, 84, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(118, 21, 93, 2, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(119, 21, 95, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(120, 21, 211, 500, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(121, 22, 2, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(122, 22, 3, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(123, 22, 59, 2, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(124, 22, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(125, 22, 69, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(126, 22, 70, 1, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(127, 22, 71, 1, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(128, 22, 211, 600, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(129, 23, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(130, 23, 8, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(131, 23, 42, 20, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(132, 23, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(133, 23, 82, 800, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(134, 23, 114, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(135, 24, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(136, 24, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(137, 24, 69, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(138, 24, 71, 1, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(139, 24, 120, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(140, 24, 312, 500, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(141, 25, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(142, 25, 3, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(143, 25, 5, 20, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(144, 25, 59, 2, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(145, 25, 180, 200, 4, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(146, 25, 312, 400, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(147, 26, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(148, 26, 6, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(149, 26, 59, 2, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(150, 26, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(151, 26, 93, 2, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(152, 26, 282, 300, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(153, 27, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(154, 27, 3, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(155, 27, 59, 2, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(156, 27, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(157, 27, 118, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(158, 27, 277, 300, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(159, 28, 2, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(160, 28, 60, 3, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(161, 28, 78, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(162, 28, 84, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(163, 28, 93, 3, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(164, 28, 233, 800, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(165, 29, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(166, 29, 3, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(167, 29, 5, 20, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(168, 29, 13, 400, 4, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(169, 29, 59, 2, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(170, 29, 312, 300, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(171, 30, 42, 50, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(172, 30, 98, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(173, 30, 100, 3, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(174, 30, 123, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(175, 30, 129, 4, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(176, 30, 317, 1000, 4, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(177, 31, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(178, 31, 6, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(179, 31, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(180, 31, 65, 800, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(181, 31, 93, 2, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(182, 31, 219, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(183, 32, 1, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(184, 32, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(185, 32, 3, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(186, 32, 6, 2, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(187, 32, 32, 100, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(188, 32, 65, 600, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(189, 32, 206, 600, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(190, 32, 319, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(191, 33, 2, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(192, 33, 6, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(193, 33, 59, 3, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(194, 33, 60, 2, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(195, 33, 93, 2, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(196, 33, 95, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(197, 33, 211, 800, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(198, 34, 8, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(199, 34, 59, 2, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(200, 34, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(201, 34, 82, 600, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(202, 34, 113, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(203, 34, 217, 500, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(204, 34, 262, 400, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(205, 34, 297, 40, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(206, 35, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(207, 35, 3, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(208, 35, 6, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(209, 35, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(210, 35, 93, 2, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(211, 35, 182, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(212, 35, 199, 800, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(213, 36, 8, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(214, 36, 59, 2, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(215, 36, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(216, 36, 82, 600, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(217, 36, 217, 400, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(218, 36, 268, 300, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(219, 36, 297, 50, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(220, 36, 300, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(221, 37, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(222, 37, 59, 2, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(223, 37, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(224, 37, 93, 2, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(225, 37, 182, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(226, 37, 216, 500, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(227, 37, 251, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(228, 37, 311, 800, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(229, 38, 1, 4, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(230, 38, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(231, 38, 3, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(232, 38, 60, 1, 14, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(233, 38, 65, 800, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(234, 38, 182, 300, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(235, 38, 219, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(236, 39, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(237, 39, 3, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(238, 39, 8, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(239, 39, 59, 2, 15, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(240, 39, 123, 1, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(241, 39, 201, 600, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(242, 40, 1, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(243, 40, 2, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(244, 40, 3, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(245, 40, 6, 2, 8, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(246, 40, 32, 100, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(247, 40, 291, 400, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(248, 41, 1, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(249, 41, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(250, 41, 5, 30, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(251, 41, 13, 300, 4, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(252, 41, 32, 250, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(253, 41, 42, 20, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(254, 42, 1, 4, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(255, 42, 13, 300, 4, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(256, 42, 32, 60, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(257, 42, 42, 80, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(258, 42, 48, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(259, 42, 50, 20, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(260, 42, 153, 50, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(261, 43, 1, 3, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(262, 43, 42, 80, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(263, 43, 50, 20, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(264, 43, 304, 500, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(265, 43, 321, 200, 4, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(266, 44, 1, 1, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(267, 44, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(268, 44, 5, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(269, 44, 32, 300, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(270, 44, 42, 120, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(271, 44, 98, 2, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(272, 44, 129, 4, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(273, 45, 1, 3, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(274, 45, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(275, 45, 5, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(276, 45, 32, 80, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(277, 45, 42, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(278, 45, 50, 30, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(279, 45, 53, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(280, 46, 1, 3, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(281, 46, 5, 80, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(282, 46, 32, 30, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(283, 46, 42, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(284, 46, 182, 200, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(285, 46, 310, 600, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(286, 47, 1, 4, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(287, 47, 32, 120, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(288, 47, 42, 120, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(289, 47, 48, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(290, 47, 170, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(291, 48, 1, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(292, 48, 5, 80, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(293, 48, 13, 200, 4, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(294, 48, 32, 250, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(295, 48, 42, 120, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(296, 48, 320, 10, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(297, 49, 1, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(298, 49, 5, 30, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(299, 49, 13, 600, 4, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(300, 49, 42, 80, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(301, 49, 48, 1, 7, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(302, 49, 251, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(303, 50, 1, 2, 10, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(304, 50, 2, 1, 9, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(305, 50, 5, 80, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(306, 50, 13, 250, 4, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(307, 50, 32, 400, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(308, 50, 42, 80, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(309, 50, 153, 150, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55'),
(310, 50, 316, 7, 1, '2026-03-31 10:51:55', '2026-03-31 10:51:55');

-- 
-- Dumping data for table favorite_recipes
--
-- Table mealrecipes.favorite_recipes does not contain any data (it is empty)

-- 
-- Dumping data for table failed_jobs
--
-- Table mealrecipes.failed_jobs does not contain any data (it is empty)

-- 
-- Dumping data for table days
--
INSERT INTO days VALUES
(1, 1, 1, 1, 1, 1, NULL, NULL),
(2, 1, 1, 11, 2, 1, NULL, NULL),
(3, 1, 1, 21, 3, 1, NULL, NULL),
(4, 1, 1, 31, 4, 1, NULL, NULL),
(5, 1, 1, 41, 5, 1, NULL, NULL),
(6, 1, 1, 32, 6, 1, NULL, NULL),
(7, 1, 1, 42, 7, 1, NULL, NULL),
(8, 2, 1, 2, 1, 1, NULL, NULL),
(9, 2, 1, 12, 2, 1, NULL, NULL),
(10, 2, 1, 22, 3, 1, NULL, NULL),
(11, 2, 1, 33, 4, 1, NULL, NULL),
(12, 2, 1, 43, 5, 1, NULL, NULL),
(13, 2, 1, 34, 6, 1, NULL, NULL),
(14, 2, 1, 44, 7, 1, NULL, NULL),
(15, 3, 1, 3, 1, 1, NULL, NULL),
(16, 3, 1, 13, 2, 1, NULL, NULL),
(17, 3, 1, 23, 3, 1, NULL, NULL),
(18, 3, 1, 35, 4, 1, NULL, NULL),
(19, 3, 1, 45, 5, 1, NULL, NULL),
(20, 3, 1, 36, 6, 1, NULL, NULL),
(21, 3, 1, 46, 7, 1, NULL, NULL),
(22, 4, 1, 4, 1, 1, NULL, NULL),
(23, 4, 1, 14, 2, 1, NULL, NULL),
(24, 4, 1, 24, 3, 1, NULL, NULL),
(25, 4, 1, 37, 4, 1, NULL, NULL),
(26, 4, 1, 47, 5, 1, NULL, NULL),
(27, 4, 1, 38, 6, 1, NULL, NULL),
(28, 4, 1, 48, 7, 1, NULL, NULL),
(29, 5, 1, 5, 1, 1, NULL, NULL),
(30, 5, 1, 15, 2, 1, NULL, NULL),
(31, 5, 1, 25, 3, 1, NULL, NULL),
(32, 5, 1, 39, 4, 1, NULL, NULL),
(33, 5, 1, 49, 5, 1, NULL, NULL),
(34, 5, 1, 40, 6, 1, NULL, NULL),
(35, 5, 1, 50, 7, 1, NULL, NULL),
(36, 6, 1, 6, 1, 1, NULL, NULL),
(37, 6, 1, 16, 2, 1, NULL, NULL),
(38, 6, 1, 26, 3, 1, NULL, NULL),
(39, 6, 1, 31, 4, 1, NULL, NULL),
(40, 6, 1, 41, 5, 1, NULL, NULL),
(41, 6, 1, 32, 6, 1, NULL, NULL),
(42, 6, 1, 42, 7, 1, NULL, NULL),
(43, 7, 1, 7, 1, 1, NULL, NULL),
(44, 7, 1, 17, 2, 1, NULL, NULL),
(45, 7, 1, 27, 3, 1, NULL, NULL),
(46, 7, 1, 33, 4, 1, NULL, NULL),
(47, 7, 1, 43, 5, 1, NULL, NULL),
(48, 7, 1, 34, 6, 1, NULL, NULL),
(49, 7, 1, 44, 7, 1, NULL, NULL);

-- 
-- Dumping data for table cache_locks
--
-- Table mealrecipes.cache_locks does not contain any data (it is empty)

-- 
-- Dumping data for table cache
--
-- Table mealrecipes.cache does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;