### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef


### login
# @name login
POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "vasarlo1@example.com",
    "password": "ronaldo"
}

###
@token = {{login.response.body.data.token}}

### logout user
POST  {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}


### get users
GET  {{host}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### get user by id
GET  {{host}}/api/users/1
Accept: application/json
Authorization: Bearer {{token}}

### post user
POST {{host}}/api/users 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name":  "Vásárló2",
    "email": "vasarlo2@example.com",
    "password": "123"
}

### patch user
PATCH {{host}}/api/users/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "No Boss"
}

### delete user
DELETE {{host}}/api/users/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### User csak önmagát törölheti
DELETE {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### A bejelentkezett user a jelszavát módosítja
PATCH {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "vasarlo2",
    "email": "vasarlo2@example.com"
}

### A bejelentkezett user egy adatát módosítja. A role tiltott
PATCH {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
     "name": "admin1"
}

### A bejelnkezett felhasználó jelszó cseréje
PATCH {{host}}/api/usersmeupdatepassword
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "oldpassword": "ronaldo",
    "newpassword": "123",
    "newpassword_confirmation": "123"
}

### A bejelentkezett user önmagát lekérheti
GET  {{host}}/api/usersme
Accept: application/json
Authorization: Bearer {{token}}



### teszt
get {{host}}/api/x

### get products
get {{host}}/api/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### get product by id
get {{host}}/api/products/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post products
POST  {{host}}/api/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "category": "Bogyós",
    "name": "f3333xx",
    "description": "Kézzel termelt egészség",
    "picture": "https:\/\/hur.webmania.cc\/img\/malna.jpg",
    "price": 8000,
    "stock": 22
}

### delete product by id
delete {{host}}/api/products/104
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post products
PATCH {{host}}/api/products/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "price": 1002,
    "stock": "eee"
}
