### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token = 12|ibiwTdr77o8ppToh1tBxIkckBNb8ECjIjLgaweTaa757cdef

### --- users
### login
# @name login
POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "felhasznalo@example.com",
    "password": "123"
}

###
@token = {{login.response.body.data.token}}

### logout user
POST  {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}


### get users
GET  {{host}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### get user by id
GET  {{host}}/api/users/1
Accept: application/json
Authorization: Bearer {{token}}

### post user
POST {{host}}/api/users 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name":  "Vásárlp1221",
    "email": "vasarlo2@example.com",
    "password": "123"
}

### patch user
PATCH {{host}}/api/users/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "No Boss"
}

### delete user
DELETE {{host}}/api/users/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### User csak önmagát törölheti
DELETE {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### A bejelentkezett user a jelszavát módosítja
PATCH {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "vasarlo2",
    "email": "vasarlo2@example.com"
}

### A bejelentkezett user egy adatát módosítja. A role tiltott
PATCH {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
     "name": "admin1"
}

### A bejelnkezett felhasználó jelszó cseréje
PATCH {{host}}/api/usersmeupdatepassword
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "oldpassword": "ronaldo",
    "newpassword": "123",
    "newpassword_confirmation": "123"
}

### A bejelentkezett user önmagát lekérheti
GET  {{host}}/api/usersme
Accept: application/json
Authorization: Bearer {{token}}



### --- units
### get units
get {{host}}/api/units
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### get unit by id
get {{host}}/api/units/15
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post units
POST  {{host}}/api/units
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "unit": "gerezdd"
}

### delete unit by id
delete {{host}}/api/units/11
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post units
PATCH {{host}}/api/units/11
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "unit": "eee"
}


### --- days


###get days
get {{host}}/api/days
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### get day by id
get {{host}}/api/days/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post days
POST  {{host}}/api/days
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "day": "kedd",
    "user_id": 1,
    "meal_of_days_id": 1,
    "recipe_id": 2,
    "meal_id": 1
}

### delete day by id
delete {{host}}/api/days/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post days
PATCH {{host}}/api/days/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "day": "Szerda"
}



### --- recipes


###get recipes
get {{host}}/api/recipes
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### get recipe by id
get {{host}}/api/recipes/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post recipes
POST  {{host}}/api/recipes
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "day": "kedd",
    "user_id": 1,
    "meal_of_days_id": 1,
    "recipe_id": 2,
    "meal_id": 1
}

### delete recipe by id
delete {{host}}/api/recipes/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post recipe
PATCH {{host}}/api/recipes/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "day": "Szerda"
}


### --- meals



###get meals
get {{host}}/api/meals/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post meals
POST  {{host}}/api/meals
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "day": "kedd",
    "user_id": 1,
    "meal_of_days_id": 1,
    "recipe_id": 2,
    "meal_id": 1
}

### delete meal by id
delete {{host}}/api/meals/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post meals
PATCH {{host}}/api/meals/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "day": "Szerda"
}


### --- ingridients
### get ingridients
get {{host}}/api/ingredients/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post ingridients
POST  {{host}}/api/ingredients
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "day": "kedd",
    "user_id": 1,
    "meal_of_days_id": 1,
    "recipe_id": 2,
    "meal_id": 1
}

### delete ingridient by id
delete {{host}}/api/ingredients/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post ingridients
PATCH {{host}}/api/ingredients/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "day": "Szerda"
}

### --- meal_requirements
###get mealrequirements
get {{host}}/api/mealrequirements/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post mealrequirements
POST  {{host}}/api/mealrequirements
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "day": "kedd",
    "user_id": 1,
    "meal_of_days_id": 1,
    "recipe_id": 2,
    "meal_id": 1
}

### delete mealrequirement by id
delete {{host}}/api/mealrequirements/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post mealrequirements
PATCH {{host}}/api/mealrequirements/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "day": "Szerda"
}

### --- meal_of_days
###get mealofdays
get {{host}}/api/mealofday/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post mealofdays
POST  {{host}}/api/mealofday
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "day": "kedd",
    "user_id": 1,
    "meal_of_days_id": 1,
    "recipe_id": 2,
    "meal_id": 1
}

### delete mealofday by id
delete {{host}}/api/mealofday/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post mealofdays
PATCH {{host}}/api/mealofday/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "day": "Szerda"
}

### --- raw_ingridients
###get rawingredients
get {{host}}/api/rawingredients/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post rawingredients
POST  {{host}}/api/rawingredients
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "day": "kedd",
    "user_id": 1,
    "meal_of_days_id": 1,
    "recipe_id": 2,
    "meal_id": 1
}

### delete rawingredient by id
delete {{host}}/api/rawingredients/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post rawingredients
PATCH {{host}}/api/rawingredients/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "day": "Szerda"
}

### --- weekdays
###get weekdays
get {{host}}/api/weekdays
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### get weekday by id
get {{host}}/api/weekdays/12
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post weekdays
POST  {{host}}/api/weekdays
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "day": "keSzerddd"
}

### delete weekday by id
delete {{host}}/api/weekdays/7
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post weekdays
PATCH {{host}}/api/weekdays/6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "day": "Szerda"
}